# Generated by Django 3.0.7 on 2020-07-03 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('querysolution', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='querysolution.Category'),
        ),
    ]
