# Generated by Django 3.0.7 on 2020-07-13 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('querysolution', '0005_auto_20200711_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='query',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solution',
            name='report',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='preference',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='query_preference', to='querysolution.Query'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference_query', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SolutionPreference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('solution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solution_preference', to='querysolution.Solution')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preference_solution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'solution', 'value')},
            },
        ),
    ]
