# Generated by Django 3.0.7 on 2020-07-17 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('querysolution', '0007_auto_20200717_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='query',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='querypreference', to='querysolution.Query'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpreferencequery', to=settings.AUTH_USER_MODEL),
        ),
    ]
