# Generated by Django 3.0.7 on 2020-07-19 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('querysolution', '0008_auto_20200718_0020'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='solutionpreference',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='solutionpreference',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='solutionpreference',
            name='user',
        ),
        migrations.RemoveField(
            model_name='query',
            name='likes',
        ),
        migrations.AddField(
            model_name='query',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='querylikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Preference',
        ),
        migrations.DeleteModel(
            name='SolutionPreference',
        ),
    ]
