# Generated by Django 3.0.7 on 2020-07-19 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('querysolution', '0009_auto_20200719_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='query',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='query',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='querydislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='dislikes',
        ),
        migrations.AddField(
            model_name='solution',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='solutiondislikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='solution',
            name='likes',
        ),
        migrations.AddField(
            model_name='solution',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='solutionlikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
