# Generated by Django 3.0.7 on 2020-07-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('querysolution', '0010_auto_20200719_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='report',
        ),
        migrations.RemoveField(
            model_name='solution',
            name='report',
        ),
    ]
