# Generated by Django 3.0.7 on 2020-07-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200702_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_content',
            field=models.TextField(null=True),
        ),
    ]
