# Generated by Django 3.0.7 on 2020-07-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0003_auto_20200702_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('Comment', 'Comment'), ('BugReport', 'BugReport'), ('Question', 'Question')], max_length=10),
        ),
    ]
