# Generated by Django 3.0.7 on 2020-07-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20200702_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('', 'Select Feedback Type'), ('Comment', 'Comment'), ('BugReport', 'BugReport'), ('Question', 'Question')], max_length=10),
        ),
    ]
