# Generated by Django 3.0.7 on 2020-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0005_auto_20200703_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeedback',
            name='feedback_type',
            field=models.CharField(choices=[('', 'Select Feedback Type'), ('Comment', 'Comment'), ('Bug Report', 'Bug Report'), ('Question', 'Question')], max_length=10),
        ),
    ]
